# This is a basic workflow to help you get started with Actions

name: Auto Re-build

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0/1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: curl -X POST ${{ secrets.hooks }}
